[package]
name = "rpgmasd"
version = "2.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["cargo", "derive"] }
clap_derive = "4.5.41"
asset-decrypter = { package = "rpgm-asset-decrypter-lib", version = "2.1.0" }
anyhow = "1.0.98"
serde_json = "1.0.141"
strum_macros = "0.27.2"
